name: api_doc
author: "Dart Team <misc@dartlang.org>"
homepage: https://github.com/dart-lang/api-doc
description: Dart API documentation browser
version: 0.0.1
dependencies:
  unittest: any
  args: any
  logging: any
  web_ui: any
  js: any
